apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: dev
type: Opaque
stringData:
  db_name: devdb
  db_user: devuser
  db_password: devpass123
---
apiVersion: v1
kind: Secret
metadata:
  name: minio-secret
  namespace: dev
type: Opaque
stringData:
  minio_user: devminio
  minio_password: devminio123
