apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: pro

resources:
  - ../base-pro
  - secrets.yaml
  - configmap.yaml
  - ingress.yaml
  - minio-ingress.yaml

patches:
  - path: app-replicas-patch.yaml

images:
  - name: flask-app
    newName: flask-app
    newTag: latest

images:
  - name: flask-app
    newName: flask-app
    newTag: latest
