apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: pro
type: Opaque
stringData:
  db_name: prodb
  db_user: prouser
  db_password: propass456
---
apiVersion: v1
kind: Secret
metadata:
  name: minio-secret
  namespace: pro
type: Opaque
stringData:
  minio_user: prominio
  minio_password: prominio456
